// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThunderPay.Database;

#nullable disable

namespace ThunderPay.Database.Migrations
{
    [DbContext(typeof(ThunderPayDbContext))]
    [Migration("20250906125701_Init_Thunderpay")]
    partial class Init_Thunderpay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("thunderpay")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThunderPay.Database.Models.MerchantDbm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationDbmId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationDbmId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "DisplayName")
                        .IsUnique();

                    b.ToTable("merchants", "thunderpay");
                });

            modelBuilder.Entity("ThunderPay.Database.Models.OrganizationDbm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("organizations", "thunderpay");
                });

            modelBuilder.Entity("ThunderPay.Database.Models.MerchantDbm", b =>
                {
                    b.HasOne("ThunderPay.Database.Models.OrganizationDbm", null)
                        .WithMany("Merchants")
                        .HasForeignKey("OrganizationDbmId");

                    b.HasOne("ThunderPay.Database.Models.OrganizationDbm", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ThunderPay.Database.Models.OrganizationDbm", b =>
                {
                    b.Navigation("Merchants");
                });
#pragma warning restore 612, 618
        }
    }
}
